version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  build:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: yarn install
      - run: yarn generate

workflows:
  version: 2
  test-build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master