version: 2

defaults: &defaults
  working_directory: ~/aws-rough
  docker:
    - image: circleci/python:3.6-jessie-node-browsers

filter_only_master: &filter_only_master
  filters:
    branches:
      only: master

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/aws-rough
          paths:
            - ./*

  build_for_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: yarn generate:test
      - persist_to_workspace:
          root: ~/aws-rough
          paths:
            - ./*

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: yarn test:unit
      - run: yarn test:e2e
      - persist_to_workspace:
          root: ~/aws-rough
          paths:
            - dist

  build_for_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: yarn generate:production
      - persist_to_workspace:
          root: ~/aws-rough
          paths:
            - ./*

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: sudo pip install awscli
      - run: aws s3 sync ./dist/ s3://aws.noplan.cc --exact-timestamps --delete --exclude "*.html" --cache-control max-age=31536000
      - run: aws s3 sync ./dist/ s3://aws.noplan.cc --exact-timestamps --delete --exclude "*" --include "*.html" --cache-control no-store
      - run: aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"

workflows:
  version: 2
  test-deploy:
    jobs:
      - install
      - build_for_test:
          requires:
            - install
      - test:
          requires:
            - build_for_test
      - build_for_production:
          requires:
            - test
      - deploy:
          <<: *filter_only_master
          requires:
            - build_for_production