version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/aws-rough
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/aws-rough
          paths:
            - ./*
  test:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/aws-rough
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: yarn test
  build:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/aws-rough
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: yarn generate
      - persist_to_workspace:
          root: ~/aws-rough
          paths:
            - dist
  deploy:
    docker:
      - image: circleci/python:3.6-jessie
    working_directory: ~/aws-rough
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: sudo pip install awscli
      - run: aws s3 sync ./dist/ s3://aws.noplan.cc --exact-timestamps --delete --exclude "*" --include "*.html" --cache-control no-store
      - run: aws s3 sync ./dist/ s3://aws.noplan.cc --exact-timestamps --delete --exclude "*" --include "*.js" --cache-control max-age=31536000
      - run: aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"

workflows:
  version: 2
  test-deploy:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - prepare
            - test
            - build
          filters:
            branches:
              only: master